/* ide_gui_wayland.c - Wayland backend of the ide GUI framework.
 *
 * Only translates Wayland events into calls to the core and implements the
 * drawing primitives of ide_gui_backend.h. Unlike X11, nobody draws for
 * us: the window is a buffer of pixels we fill ourselves - rects and
 * shadows directly, text with FreeType (the font found by fontconfig, its
 * glyphs cached) - and hand to the compositor, only the part that changed.
 * The title bar is the compositor's (xdg-decoration) where it offers one.
 * Key repeat is ours too: Wayland sends a key once.
 *
 * Build: gcc ... ide_gui_wayland.c -lwayland-client -lwayland-cursor
 *            -lxkbcommon -lfontconfig -lfreetype $(pkg-config --cflags freetype2)
 */
#define _GNU_SOURCE   /* memfd_create */

#include "ide_gui_backend.h"
#include "../version.h"

#include <wayland-client.h>
#include <wayland-cursor.h>
#include <xkbcommon/xkbcommon.h>
#include <xkbcommon/xkbcommon-compose.h>
#include <fontconfig/fontconfig.h>
#include <ft2build.h>
#include FT_FREETYPE_H
#include <linux/input-event-codes.h>

#include "wayland/xdg-shell-client-protocol.h"
#include "wayland/xdg-decoration-client-protocol.h"
/* the protocols' marshalling tables, generated by wayland-scanner */
#include "wayland/xdg-shell-protocol.c"
#include "wayland/xdg-decoration-protocol.c"

#include <errno.h>
#include <fcntl.h>
#include <locale.h>
#include <poll.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <sys/mman.h>
#include <time.h>
#include <unistd.h>

#define DEFAULT_FONT_PT 11
#define DEFAULT_COLS 120
#define DEFAULT_ROWS 30
#define SMALL_FONT_PERCENT 85
#define DOUBLE_CLICK_MS 400
#define DPI 96.0

static const char* const font_candidates[] = {
    "DejaVu Sans Mono", "Liberation Mono", "Noto Sans Mono", "Ubuntu Mono", "Monospace",
};

#define CANDIDATE_COUNT ((int)(sizeof font_candidates / sizeof font_candidates[0]))

/* --- Fonts: FreeType, glyphs rendered once and kept --- */

struct glyph
{
    uint32_t cp;
    int left, top;            /* the bitmap's offset from the pen, px (top: above the baseline) */
    int w, h;
    unsigned char* alpha;     /* w * h coverage; NULL: nothing to draw */
};

struct font
{
    FT_Face face;
    struct gui_metrics metrics;
    struct glyph* glyphs;     /* open hashing on cp */
    int cap, count;
};

/* --- The window --- */

struct shm_buffer
{
    struct wl_buffer* buffer;
    uint32_t* pixels;
    int w, h;
    size_t size;
    int busy;                    /* the compositor still reads it */
    struct gui_rect stale;       /* what changed in the canvas since it was filled */
};

struct gui_canvas
{
    uint32_t* pixels;            /* the back buffer: what the core draws on, XRGB */
    int w, h;
    int clip_on, cx, cy, cw, ch;
    struct font main, small_font;
    FT_Library ft;
    int pt;
    const char* family;          /* NULL: the first installed candidate */
    char* clip_text;             /* what we offer as the selection */
    struct wl_window* win;
};

struct wl_window
{
    struct gui_canvas canvas;    /* first: gui_clipboard_* get only this */
    struct gui_app* app;
    struct wl_display* display;
    struct wl_registry* registry;
    struct wl_compositor* compositor;
    struct wl_shm* shm;
    struct wl_seat* seat;
    struct wl_pointer* pointer;
    struct wl_keyboard* keyboard;
    struct xdg_wm_base* wm_base;
    struct zxdg_decoration_manager_v1* decoration_manager;
    struct wl_data_device_manager* data_manager;
    struct wl_data_device* data_device;
    struct wl_data_offer* selection_offer;   /* what another client offers to paste */
    struct wl_data_source* source;           /* ours, while we own the selection */
    struct wl_surface* surface;
    struct xdg_surface* xdg_surface;
    struct xdg_toplevel* toplevel;
    struct shm_buffer buffers[2];
    int configured;              /* the first configure came: we may draw */
    int want_w, want_h;          /* the size the last configure asked for */
    int frame_pending;           /* something to show waits for a free buffer */
    struct gui_rect damage;      /* what changed since the last commit */
    /* input */
    struct xkb_context* xkb;
    struct xkb_keymap* keymap;
    struct xkb_state* xkb_state;
    struct xkb_compose_table* compose_table;
    struct xkb_compose_state* compose;
    uint32_t serial;             /* the last input event's: set_selection needs one */
    int mouse_x, mouse_y;
    uint32_t last_click_time;
    int last_click_x, last_click_y;
    struct wl_cursor_theme* cursor_theme;
    struct wl_surface* cursor_surface;
    uint32_t pointer_serial;
    enum gui_cursor cursor;
    int cursor_shown;
    int repeat_rate, repeat_delay;   /* per second, ms */
    uint32_t repeat_key;         /* the key held for repeat; 0 none */
    long long repeat_due;
    int offered_fonts[16];
    int font_count;
    int timer_ms;
    long long timer_due;
    int running;
    int pending;                 /* events taken since the last refresh */
};

static long long now_ms(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return (long long)ts.tv_sec * 1000 + ts.tv_nsec / 1000000;
}

/* fontconfig substitutes instead of failing, so a family is installed only
 * if the match has that very name. Its file into *path (malloc'ed). */
static int font_file(const char* name, char** path)
{
    FcPattern* pat = FcNameParse((const FcChar8*)name);
    if (!pat)
        return 0;
    FcPatternAddInteger(pat, FC_SPACING, FC_MONO);
    FcConfigSubstitute(NULL, pat, FcMatchPattern);
    FcDefaultSubstitute(pat);
    FcResult result;
    FcPattern* match = FcFontMatch(NULL, pat, &result);
    FcPatternDestroy(pat);
    if (!match)
        return 0;
    FcChar8* family = NULL;
    FcChar8* file = NULL;
    int ok = FcPatternGetString(match, FC_FAMILY, 0, &family) == FcResultMatch &&
             FcPatternGetString(match, FC_FILE, 0, &file) == FcResultMatch &&
             (strcasecmp((const char*)family, name) == 0 || strcmp(name, "Monospace") == 0);
    if (ok && path)
        *path = strdup((const char*)file);
    FcPatternDestroy(match);
    return ok;
}

static void font_free(struct font* f)
{
    for (int i = 0; i < f->cap; i++)
        free(f->glyphs[i].alpha);
    free(f->glyphs);
    if (f->face)
        FT_Done_Face(f->face);
    memset(f, 0, sizeof *f);
}

static int font_open(struct gui_canvas* c, struct font* f, int pt)
{
    const char* family = c->family;
    char* path = NULL;
    for (int i = 0; !family && i < CANDIDATE_COUNT; i++)
    {
        if (font_file(font_candidates[i], NULL))
            family = font_candidates[i];
    }
    if (!family || !font_file(family, &path))
        return 0;
    FT_Face face;
    int err = FT_New_Face(c->ft, path, 0, &face);
    free(path);
    if (err)
        return 0;
    FT_Set_Char_Size(face, 0, pt * 64, (FT_UInt)DPI, (FT_UInt)DPI);
    memset(f, 0, sizeof *f);
    f->face = face;
    int adv = 0;
    if (FT_Load_Char(face, 'M', FT_LOAD_DEFAULT) == 0)
        adv = (int)((face->glyph->advance.x + 32) >> 6);
    int ascent = (int)((face->size->metrics.ascender + 63) >> 6);
    int descent = (int)((-face->size->metrics.descender + 63) >> 6);
    f->metrics.cell_w = adv > 0 ? adv : 1;
    f->metrics.cell_h = ascent + descent > 0 ? ascent + descent : 1;
    f->metrics.ascent = ascent;
    return 1;
}

static const struct glyph* font_glyph(struct font* f, uint32_t cp)
{
    if (f->count * 2 >= f->cap)
    {
        int cap = f->cap ? f->cap * 2 : 256;
        struct glyph* g = calloc((size_t)cap, sizeof *g);
        if (!g)
            abort();
        for (int i = 0; i < f->cap; i++)
        {
            if (!f->glyphs[i].cp)
                continue;
            int k = (int)(f->glyphs[i].cp * 2654435761u % (unsigned)cap);
            while (g[k].cp)
                k = (k + 1) % cap;
            g[k] = f->glyphs[i];
        }
        free(f->glyphs);
        f->glyphs = g;
        f->cap = cap;
    }
    int k = (int)(cp * 2654435761u % (unsigned)f->cap);
    while (f->glyphs[k].cp && f->glyphs[k].cp != cp)
        k = (k + 1) % f->cap;
    struct glyph* g = &f->glyphs[k];
    if (g->cp == cp)
        return g;
    g->cp = cp;
    f->count++;
    FT_UInt index = FT_Get_Char_Index(f->face, cp);
    if (!index || FT_Load_Glyph(f->face, index, FT_LOAD_DEFAULT) ||
        FT_Render_Glyph(f->face->glyph, FT_RENDER_MODE_NORMAL))
        return g;   /* not in the font: nothing drawn */
    FT_Bitmap* bm = &f->face->glyph->bitmap;
    g->left = f->face->glyph->bitmap_left;
    g->top = f->face->glyph->bitmap_top;
    g->w = (int)bm->width;
    g->h = (int)bm->rows;
    if (g->w > 0 && g->h > 0)
    {
        g->alpha = malloc((size_t)g->w * (size_t)g->h);
        if (g->alpha)
        {
            for (int y = 0; y < g->h; y++)
                memcpy(g->alpha + y * g->w, bm->buffer + y * bm->pitch, (size_t)g->w);
        }
    }
    return g;
}

static void offer_fonts(struct wl_window* win)
{
    const char* names[CANDIDATE_COUNT];
    win->font_count = 0;
    for (int i = 0; i < CANDIDATE_COUNT; i++)
    {
        if (!font_file(font_candidates[i], NULL))
            continue;
        names[win->font_count] = font_candidates[i];
        win->offered_fonts[win->font_count++] = i;
    }
    gui_app_set_fonts(win->app, names, win->font_count, 0);
}

/* (Re)creates both fonts from canvas->pt: they always exist together. */
static int apply_font(struct gui_canvas* c)
{
    int small_pt = (c->pt * SMALL_FONT_PERCENT + 50) / 100;
    struct font main, small_font;
    if (!font_open(c, &main, c->pt))
        return 0;
    if (!font_open(c, &small_font, small_pt > 0 ? small_pt : 1))
    {
        font_free(&main);
        return 0;
    }
    font_free(&c->main);
    font_free(&c->small_font);
    c->main = main;
    c->small_font = small_font;
    return 1;
}

/* --- Drawing primitives (ide_gui_backend.h): pixels, by hand --- */

struct gui_metrics gui_font_metrics(struct gui_canvas* c, enum gui_font font)
{
    return font == GUI_FONT_SMALL ? c->small_font.metrics : c->main.metrics;
}

int gui_scrollbar_size(struct gui_canvas* c)
{
    int size = (10 * c->pt + DEFAULT_FONT_PT / 2) / DEFAULT_FONT_PT;
    return size > 2 ? size : 2;
}

void gui_set_clip(struct gui_canvas* c, int x, int y, int w, int h)
{
    c->clip_on = w > 0 && h > 0;
    c->cx = x;
    c->cy = y;
    c->cw = w;
    c->ch = h;
}

/* The rect inside the canvas and the clip; 0 if nothing is left. */
static int clip_rect(const struct gui_canvas* c, int* x, int* y, int* w, int* h)
{
    int x0 = *x, y0 = *y, x1 = *x + *w, y1 = *y + *h;
    if (c->clip_on)
    {
        if (x0 < c->cx) x0 = c->cx;
        if (y0 < c->cy) y0 = c->cy;
        if (x1 > c->cx + c->cw) x1 = c->cx + c->cw;
        if (y1 > c->cy + c->ch) y1 = c->cy + c->ch;
    }
    if (x0 < 0) x0 = 0;
    if (y0 < 0) y0 = 0;
    if (x1 > c->w) x1 = c->w;
    if (y1 > c->h) y1 = c->h;
    *x = x0;
    *y = y0;
    *w = x1 - x0;
    *h = y1 - y0;
    return *w > 0 && *h > 0;
}

void gui_fill_rect(struct gui_canvas* c, int x, int y, int w, int h, uint32_t rgb)
{
    if (!clip_rect(c, &x, &y, &w, &h))
        return;
    uint32_t px = 0xFF000000u | (rgb & 0xFFFFFF);
    for (int row = 0; row < h; row++)
    {
        uint32_t* p = c->pixels + (size_t)(y + row) * (size_t)c->w + (size_t)x;
        for (int i = 0; i < w; i++)
            p[i] = px;
    }
}

void gui_shade_rect(struct gui_canvas* c, int x, int y, int w, int h, int alpha)
{
    if (!clip_rect(c, &x, &y, &w, &h))
        return;
    unsigned keep = 255u - (unsigned)alpha;
    for (int row = 0; row < h; row++)
    {
        uint32_t* p = c->pixels + (size_t)(y + row) * (size_t)c->w + (size_t)x;
        for (int i = 0; i < w; i++)
        {
            uint32_t v = p[i];
            uint32_t r = ((v >> 16) & 0xFF) * keep / 255, g = ((v >> 8) & 0xFF) * keep / 255, b = (v & 0xFF) * keep / 255;
            p[i] = 0xFF000000u | r << 16 | g << 8 | b;
        }
    }
}

void gui_draw_text(struct gui_canvas* c, int x, int y, const uint32_t* cps, int count,
                   uint32_t fg, uint32_t bg, enum gui_font font)
{
    struct font* f = font == GUI_FONT_SMALL ? &c->small_font : &c->main;
    const struct gui_metrics* m = &f->metrics;
    gui_fill_rect(c, x, y, count * m->cell_w, m->cell_h, bg);
    /* the glyphs stay inside the run's rect, as the backend contract says */
    int rx = x, ry = y, rw = count * m->cell_w, rh = m->cell_h;
    if (!clip_rect(c, &rx, &ry, &rw, &rh))
        return;
    unsigned fr = (fg >> 16) & 0xFF, fgg = (fg >> 8) & 0xFF, fb = fg & 0xFF;
    for (int i = 0; i < count; i++)
    {
        uint32_t cp = cps[i];
        if (cp == ' ' || cp == 0)
            continue;
        const struct glyph* g = font_glyph(f, cp);
        if (!g->alpha)
            continue;
        int gx = x + i * m->cell_w + g->left;
        int gy = y + m->ascent - g->top;
        for (int row = 0; row < g->h; row++)
        {
            int py = gy + row;
            if (py < ry || py >= ry + rh)
                continue;
            uint32_t* line = c->pixels + (size_t)py * (size_t)c->w;
            const unsigned char* a = g->alpha + row * g->w;
            for (int col = 0; col < g->w; col++)
            {
                int px = gx + col;
                unsigned k = a[col];
                if (!k || px < rx || px >= rx + rw)
                    continue;
                uint32_t v = line[px];
                unsigned r = (fr * k + ((v >> 16) & 0xFF) * (255 - k)) / 255;
                unsigned gg = (fgg * k + ((v >> 8) & 0xFF) * (255 - k)) / 255;
                unsigned b = (fb * k + (v & 0xFF) * (255 - k)) / 255;
                line[px] = 0xFF000000u | r << 16 | gg << 8 | b;
            }
        }
    }
}

/* --- Buffers: the canvas, and the compositor's copies of it --- */

static void unite(struct gui_rect* r, const struct gui_rect* add)
{
    if (add->w <= 0 || add->h <= 0)
        return;
    if (r->w <= 0 || r->h <= 0)
    {
        *r = *add;
        return;
    }
    int x1 = r->x + r->w > add->x + add->w ? r->x + r->w : add->x + add->w;
    int y1 = r->y + r->h > add->y + add->h ? r->y + r->h : add->y + add->h;
    r->x = r->x < add->x ? r->x : add->x;
    r->y = r->y < add->y ? r->y : add->y;
    r->w = x1 - r->x;
    r->h = y1 - r->y;
}

static void buffer_release(void* data, struct wl_buffer* buffer)
{
    (void)buffer;
    struct shm_buffer* b = data;
    b->busy = 0;
}

static const struct wl_buffer_listener buffer_listener = { buffer_release };

static void buffer_destroy(struct shm_buffer* b)
{
    if (b->buffer)
        wl_buffer_destroy(b->buffer);
    if (b->pixels)
        munmap(b->pixels, b->size);
    memset(b, 0, sizeof *b);
}

static int buffer_create(struct wl_window* win, struct shm_buffer* b, int w, int h)
{
    int stride = w * 4;
    size_t size = (size_t)stride * (size_t)h;
    int fd = memfd_create("cakeide", MFD_CLOEXEC);
    if (fd < 0 || ftruncate(fd, (off_t)size) < 0)
    {
        if (fd >= 0)
            close(fd);
        return 0;
    }
    void* data = mmap(NULL, size, PROT_READ | PROT_WRITE, MAP_SHARED, fd, 0);
    if (data == MAP_FAILED)
    {
        close(fd);
        return 0;
    }
    struct wl_shm_pool* pool = wl_shm_create_pool(win->shm, fd, (int32_t)size);
    b->buffer = wl_shm_pool_create_buffer(pool, 0, w, h, stride, WL_SHM_FORMAT_XRGB8888);
    wl_shm_pool_destroy(pool);
    close(fd);
    b->pixels = data;
    b->size = size;
    b->w = w;
    b->h = h;
    b->busy = 0;
    b->stale = (struct gui_rect){ 0, 0, w, h };   /* a new buffer: all of it to fill */
    wl_buffer_add_listener(b->buffer, &buffer_listener, b);
    return 1;
}

/* The canvas at the new size; its old contents are lost, so the core paints
 * everything next. */
static void resize_canvas(struct wl_window* win, int w, int h)
{
    struct gui_canvas* c = &win->canvas;
    if (w < 1) w = 1;
    if (h < 1) h = 1;
    if (c->pixels && w == c->w && h == c->h)
        return;
    free(c->pixels);
    c->pixels = calloc((size_t)w * (size_t)h, 4);
    if (!c->pixels)
        abort();
    c->w = w;
    c->h = h;
    for (int i = 0; i < 2; i++)
        buffer_destroy(&win->buffers[i]);   /* made again at the new size when needed */
    if (win->app)
    {
        gui_app_resize(win->app, w, h);
        gui_app_invalidate(win->app);
    }
}

/* What changed goes to a free buffer, which is handed to the compositor.
 * Each buffer remembers what changed since it was last filled, so only
 * that is copied into it - not the whole window. */
static void present(struct wl_window* win)
{
    struct gui_canvas* c = &win->canvas;
    if (!win->configured || win->damage.w <= 0)
        return;
    struct shm_buffer* b = NULL;
    for (int i = 0; i < 2 && !b; i++)
    {
        if (!win->buffers[i].busy)
            b = &win->buffers[i];
    }
    if (!b)
    {
        win->frame_pending = 1;   /* shown when the compositor gives one back */
        return;
    }
    if (!b->buffer && !buffer_create(win, b, c->w, c->h))
        return;
    for (int i = 0; i < 2; i++)
        unite(&win->buffers[i].stale, &win->damage);
    struct gui_rect s = b->stale;
    for (int row = s.y; row < s.y + s.h && row < c->h; row++)
        memcpy(b->pixels + (size_t)row * (size_t)c->w + (size_t)s.x,
               c->pixels + (size_t)row * (size_t)c->w + (size_t)s.x, (size_t)s.w * 4);
    b->stale = (struct gui_rect){ 0, 0, 0, 0 };
    b->busy = 1;
    wl_surface_attach(win->surface, b->buffer, 0, 0);
    wl_surface_damage_buffer(win->surface, win->damage.x, win->damage.y, win->damage.w, win->damage.h);
    wl_surface_commit(win->surface);
    win->damage = (struct gui_rect){ 0, 0, 0, 0 };
    win->frame_pending = 0;
}

static void set_cursor(struct wl_window* win, enum gui_cursor cursor);

/* Applies what the app asked for (quit, timer, font, zoom), lets the core
 * paint whatever changed and shows it. */
static void refresh(struct wl_window* win)
{
    struct gui_canvas* c = &win->canvas;
    if (gui_app_should_quit(win->app))
    {
        win->running = 0;
        return;
    }
    int ms;
    if (gui_app_take_timer(win->app, &ms))
    {
        win->timer_ms = ms > 0 ? ms : 0;
        win->timer_due = now_ms() + win->timer_ms;
    }
    int family = gui_app_take_font(win->app);
    if (family >= 0 && family < win->font_count)
    {
        c->family = font_candidates[win->offered_fonts[family]];
        if (apply_font(c))
            gui_app_font_changed(win->app, c);
    }
    int zoom = gui_app_take_zoom(win->app);
    if (zoom)
    {
        int pt = c->pt + zoom;
        c->pt = pt < 6 ? 6 : pt > 40 ? 40 : pt;
        if (apply_font(c))
            gui_app_font_changed(win->app, c);
    }
    if (!win->configured)
        return;
    struct gui_rect r;
    if (gui_app_paint(win->app, c, &r))
        unite(&win->damage, &r);
    present(win);
    set_cursor(win, gui_app_cursor(win->app));
}

/* The event to the app; the paint waits until every queued event is taken
 * (the main loop), so a burst costs one frame. */
static void post(struct wl_window* win, const struct gui_event* ev)
{
    gui_app_event(win->app, ev);
    win->pending = 1;
}

/* --- Clipboard (ide_gui_backend.h): the selection of wl_data_device --- */

#define TEXT_MIME "text/plain;charset=utf-8"

static void source_target(void* data, struct wl_data_source* s, const char* mime)
{
    (void)data; (void)s; (void)mime;
}

static void source_send(void* data, struct wl_data_source* s, const char* mime, int32_t fd)
{
    (void)s; (void)mime;
    struct wl_window* win = data;
    const char* text = win->canvas.clip_text ? win->canvas.clip_text : "";
    size_t len = strlen(text), done = 0;
    while (done < len)
    {
        ssize_t n = write(fd, text + done, len - done);
        if (n <= 0)
            break;
        done += (size_t)n;
    }
    close(fd);
}

static void source_cancelled(void* data, struct wl_data_source* s)
{
    struct wl_window* win = data;
    wl_data_source_destroy(s);
    if (win->source == s)
        win->source = NULL;
}

static const struct wl_data_source_listener source_listener = {
    .target = source_target,
    .send = source_send,
    .cancelled = source_cancelled,
};

void gui_clipboard_set(struct gui_canvas* c, const char* utf8)
{
    struct wl_window* win = c->win;
    free(c->clip_text);
    c->clip_text = strdup(utf8);
    if (!win->data_manager || !win->data_device)
        return;
    if (win->source)
        wl_data_source_destroy(win->source);
    win->source = wl_data_device_manager_create_data_source(win->data_manager);
    wl_data_source_offer(win->source, TEXT_MIME);
    wl_data_source_offer(win->source, "text/plain");
    wl_data_source_offer(win->source, "UTF8_STRING");
    wl_data_source_add_listener(win->source, &source_listener, win);
    wl_data_device_set_selection(win->data_device, win->source, win->serial);
}

char* gui_clipboard_get(struct gui_canvas* c)
{
    struct wl_window* win = c->win;
    if (win->source && c->clip_text)
        return strdup(c->clip_text);   /* ours: no round trip through the compositor */
    if (!win->selection_offer)
        return NULL;
    int fds[2];
    if (pipe(fds) != 0)
        return NULL;
    wl_data_offer_receive(win->selection_offer, TEXT_MIME, fds[1]);
    close(fds[1]);
    wl_display_flush(win->display);
    size_t len = 0, cap = 4096;
    char* text = malloc(cap + 1);
    /* the other client writes it; up to 1 s */
    for (;;)
    {
        struct pollfd p = { fds[0], POLLIN, 0 };
        if (poll(&p, 1, 1000) <= 0)
            break;
        if (text && len + 4096 > cap)
        {
            char* bigger = realloc(text, cap * 2 + 1);
            if (!bigger)
                break;
            text = bigger;
            cap *= 2;
        }
        ssize_t n = read(fds[0], text + len, cap - len);
        if (n <= 0)
            break;
        len += (size_t)n;
    }
    close(fds[0]);
    if (!text)
        return NULL;
    size_t o = 0;
    for (size_t i = 0; i < len; i++)
    {
        if (text[i] != '\r')   /* "\r\n" from other programs back to '\n' */
            text[o++] = text[i];
    }
    text[o] = '\0';
    return text;
}

static void offer_offer(void* data, struct wl_data_offer* offer, const char* mime)
{
    (void)data; (void)offer; (void)mime;
}

static const struct wl_data_offer_listener offer_listener = { .offer = offer_offer };

static void device_data_offer(void* data, struct wl_data_device* dev, struct wl_data_offer* offer)
{
    (void)data; (void)dev;
    wl_data_offer_add_listener(offer, &offer_listener, NULL);
}

static void device_enter(void* data, struct wl_data_device* dev, uint32_t serial, struct wl_surface* s,
                         wl_fixed_t x, wl_fixed_t y, struct wl_data_offer* offer)
{
    (void)data; (void)dev; (void)serial; (void)s; (void)x; (void)y; (void)offer;
}

static void device_leave(void* data, struct wl_data_device* dev)
{
    (void)data; (void)dev;
}

static void device_motion(void* data, struct wl_data_device* dev, uint32_t time, wl_fixed_t x, wl_fixed_t y)
{
    (void)data; (void)dev; (void)time; (void)x; (void)y;
}

static void device_drop(void* data, struct wl_data_device* dev)
{
    (void)data; (void)dev;
}

static void device_selection(void* data, struct wl_data_device* dev, struct wl_data_offer* offer)
{
    (void)dev;
    struct wl_window* win = data;
    if (win->selection_offer)
        wl_data_offer_destroy(win->selection_offer);
    win->selection_offer = offer;
}

static const struct wl_data_device_listener device_listener = {
    .data_offer = device_data_offer,
    .enter = device_enter,
    .leave = device_leave,
    .motion = device_motion,
    .drop = device_drop,
    .selection = device_selection,
};

/* --- Pointer --- */

static void set_cursor(struct wl_window* win, enum gui_cursor cursor)
{
    if (!win->pointer || !win->cursor_theme || !win->pointer_serial)
        return;
    if (win->cursor_shown && cursor == win->cursor)
        return;
    static const char* const names[][2] = {
        { "left_ptr", "default" }, { "sb_h_double_arrow", "ew-resize" }, { "sb_v_double_arrow", "ns-resize" },
        { "bottom_right_corner", "nwse-resize" }, { "bottom_left_corner", "nesw-resize" },
    };
    struct wl_cursor* wc = wl_cursor_theme_get_cursor(win->cursor_theme, names[cursor][0]);
    if (!wc)
        wc = wl_cursor_theme_get_cursor(win->cursor_theme, names[cursor][1]);
    if (!wc)
        wc = wl_cursor_theme_get_cursor(win->cursor_theme, "left_ptr");
    if (!wc || wc->image_count == 0)
        return;
    struct wl_cursor_image* img = wc->images[0];
    struct wl_buffer* buffer = wl_cursor_image_get_buffer(img);
    wl_pointer_set_cursor(win->pointer, win->pointer_serial, win->cursor_surface,
                          (int32_t)img->hotspot_x, (int32_t)img->hotspot_y);
    wl_surface_attach(win->cursor_surface, buffer, 0, 0);
    wl_surface_damage_buffer(win->cursor_surface, 0, 0, (int32_t)img->width, (int32_t)img->height);
    wl_surface_commit(win->cursor_surface);
    win->cursor = cursor;
    win->cursor_shown = 1;
}

static int current_mods(struct wl_window* win)
{
    if (!win->xkb_state)
        return 0;
    struct xkb_state* s = win->xkb_state;
    return (xkb_state_mod_name_is_active(s, XKB_MOD_NAME_SHIFT, XKB_STATE_MODS_EFFECTIVE) > 0 ? GUI_MOD_SHIFT : 0) |
           (xkb_state_mod_name_is_active(s, XKB_MOD_NAME_CTRL, XKB_STATE_MODS_EFFECTIVE) > 0 ? GUI_MOD_CTRL : 0) |
           (xkb_state_mod_name_is_active(s, XKB_MOD_NAME_ALT, XKB_STATE_MODS_EFFECTIVE) > 0 ? GUI_MOD_ALT : 0);
}

static void pointer_enter(void* data, struct wl_pointer* p, uint32_t serial, struct wl_surface* s,
                          wl_fixed_t x, wl_fixed_t y)
{
    (void)p; (void)s;
    struct wl_window* win = data;
    win->pointer_serial = serial;
    win->cursor_shown = 0;
    win->mouse_x = wl_fixed_to_int(x);
    win->mouse_y = wl_fixed_to_int(y);
    set_cursor(win, gui_app_cursor(win->app));
}

static void pointer_leave(void* data, struct wl_pointer* p, uint32_t serial, struct wl_surface* s)
{
    (void)p; (void)serial; (void)s;
    struct wl_window* win = data;
    struct gui_event ev = { 0 };
    ev.type = GUI_EVENT_MOUSE_LEAVE;
    post(win, &ev);
}

static void pointer_motion(void* data, struct wl_pointer* p, uint32_t time, wl_fixed_t x, wl_fixed_t y)
{
    (void)p; (void)time;
    struct wl_window* win = data;
    win->mouse_x = wl_fixed_to_int(x);
    win->mouse_y = wl_fixed_to_int(y);
    struct gui_event ev = { 0 };
    ev.type = GUI_EVENT_MOUSE_MOVE;
    ev.x = win->mouse_x;
    ev.y = win->mouse_y;
    ev.mods = current_mods(win);
    post(win, &ev);
}

static void pointer_button(void* data, struct wl_pointer* p, uint32_t serial, uint32_t time,
                           uint32_t button, uint32_t state)
{
    (void)p;
    struct wl_window* win = data;
    win->serial = serial;
    if (button != BTN_LEFT && button != BTN_RIGHT)
        return;
    struct gui_event ev = { 0 };
    ev.x = win->mouse_x;
    ev.y = win->mouse_y;
    ev.mods = current_mods(win);
    ev.button = button == BTN_LEFT ? 0 : 1;
    ev.type = state == WL_POINTER_BUTTON_STATE_PRESSED ? GUI_EVENT_MOUSE_DOWN : GUI_EVENT_MOUSE_UP;
    if (ev.type == GUI_EVENT_MOUSE_DOWN && ev.button == 0)
    {
        /* Wayland has no double click: a second press soon, a few px away */
        int near = abs(ev.x - win->last_click_x) <= 4 && abs(ev.y - win->last_click_y) <= 4;
        ev.double_click = near && win->last_click_time && time - win->last_click_time < DOUBLE_CLICK_MS;
        win->last_click_time = ev.double_click ? 0 : time;
        win->last_click_x = ev.x;
        win->last_click_y = ev.y;
    }
    post(win, &ev);
}

static void pointer_axis(void* data, struct wl_pointer* p, uint32_t time, uint32_t axis, wl_fixed_t value)
{
    (void)p; (void)time;
    struct wl_window* win = data;
    struct gui_event ev = { 0 };
    ev.type = GUI_EVENT_WHEEL;
    ev.x = win->mouse_x;
    ev.y = win->mouse_y;
    ev.mods = current_mods(win);
    /* a notch is 10 here, 120 for the core - away from the user positive */
    if (axis == WL_POINTER_AXIS_VERTICAL_SCROLL)
        ev.wheel = (int)(-wl_fixed_to_double(value) * 12.0);
    else
        ev.hwheel = (int)(wl_fixed_to_double(value) * 12.0);
    if (ev.wheel || ev.hwheel)
        post(win, &ev);
}

static void pointer_frame(void* data, struct wl_pointer* p) { (void)data; (void)p; }
static void pointer_axis_source(void* data, struct wl_pointer* p, uint32_t s) { (void)data; (void)p; (void)s; }
static void pointer_axis_stop(void* data, struct wl_pointer* p, uint32_t t, uint32_t a) { (void)data; (void)p; (void)t; (void)a; }
static void pointer_axis_discrete(void* data, struct wl_pointer* p, uint32_t a, int32_t d) { (void)data; (void)p; (void)a; (void)d; }

static const struct wl_pointer_listener pointer_listener = {
    .enter = pointer_enter,
    .leave = pointer_leave,
    .motion = pointer_motion,
    .button = pointer_button,
    .axis = pointer_axis,
    .frame = pointer_frame,
    .axis_source = pointer_axis_source,
    .axis_stop = pointer_axis_stop,
    .axis_discrete = pointer_axis_discrete,
};

/* --- Keyboard: xkbcommon, accents through compose, repeat by us --- */

/* A keysym as a gui key code, or 0 for keys the framework ignores. */
static int map_keysym(xkb_keysym_t sym)
{
    if (sym >= XKB_KEY_a && sym <= XKB_KEY_z) return (int)(sym - XKB_KEY_a + 'A');
    if (sym >= XKB_KEY_A && sym <= XKB_KEY_Z) return (int)sym;
    if (sym >= XKB_KEY_0 && sym <= XKB_KEY_9) return (int)sym;
    if (sym >= XKB_KEY_F1 && sym <= XKB_KEY_F12) return GUI_KEY_F1 + (int)(sym - XKB_KEY_F1);
    switch (sym)
    {
    case XKB_KEY_Escape: return GUI_KEY_ESCAPE;
    case XKB_KEY_Return: case XKB_KEY_KP_Enter: return GUI_KEY_ENTER;
    case XKB_KEY_Tab: case XKB_KEY_ISO_Left_Tab: return GUI_KEY_TAB;
    case XKB_KEY_BackSpace: return GUI_KEY_BACKSPACE;
    case XKB_KEY_Delete: case XKB_KEY_KP_Delete: return GUI_KEY_DELETE;
    case XKB_KEY_Insert: case XKB_KEY_KP_Insert: return GUI_KEY_INSERT;
    case XKB_KEY_Home: case XKB_KEY_KP_Home: return GUI_KEY_HOME;
    case XKB_KEY_End: case XKB_KEY_KP_End: return GUI_KEY_END;
    case XKB_KEY_Page_Up: case XKB_KEY_KP_Page_Up: return GUI_KEY_PAGEUP;
    case XKB_KEY_Page_Down: case XKB_KEY_KP_Page_Down: return GUI_KEY_PAGEDOWN;
    case XKB_KEY_Left: case XKB_KEY_KP_Left: return GUI_KEY_LEFT;
    case XKB_KEY_Right: case XKB_KEY_KP_Right: return GUI_KEY_RIGHT;
    case XKB_KEY_Up: case XKB_KEY_KP_Up: return GUI_KEY_UP;
    case XKB_KEY_Down: case XKB_KEY_KP_Down: return GUI_KEY_DOWN;
    case XKB_KEY_space: return ' ';
    case XKB_KEY_plus: case XKB_KEY_equal: case XKB_KEY_KP_Add: return '+';
    case XKB_KEY_minus: case XKB_KEY_KP_Subtract: return '-';
    }
    return 0;
}

static uint32_t utf8_decode(const char* s, int* len)
{
    const unsigned char* u = (const unsigned char*)s;
    if (u[0] < 0x80) { *len = 1; return u[0]; }
    if ((u[0] & 0xE0) == 0xC0 && u[1]) { *len = 2; return (uint32_t)(u[0] & 0x1F) << 6 | (u[1] & 0x3F); }
    if ((u[0] & 0xF0) == 0xE0 && u[1] && u[2])
    { *len = 3; return (uint32_t)(u[0] & 0x0F) << 12 | (uint32_t)(u[1] & 0x3F) << 6 | (u[2] & 0x3F); }
    if ((u[0] & 0xF8) == 0xF0 && u[1] && u[2] && u[3])
    {
        *len = 4;
        return (uint32_t)(u[0] & 0x07) << 18 | (uint32_t)(u[1] & 0x3F) << 12 | (uint32_t)(u[2] & 0x3F) << 6 | (u[3] & 0x3F);
    }
    *len = 1;
    return 0;
}

static void post_chars(struct wl_window* win, const char* text)
{
    for (const char* p = text; *p;)
    {
        int len;
        uint32_t ch = utf8_decode(p, &len);
        p += len;
        if (ch < 32 || ch == 127)
            continue;
        struct gui_event ev = { 0 };
        ev.type = GUI_EVENT_CHAR;
        ev.ch = ch;
        post(win, &ev);
    }
}

/* Like X11: a key event for keys and shortcuts, then a char event for what
 * the key types - none with Ctrl or Alt held. `xkb_key` is the evdev code + 8. */
static void key_down(struct wl_window* win, uint32_t xkb_key)
{
    xkb_keysym_t sym = xkb_state_key_get_one_sym(win->xkb_state, xkb_key);
    int mods = current_mods(win);
    int key = map_keysym(xkb_keysym_to_lower(sym) == sym ? sym : xkb_keysym_to_lower(sym));
    if (key)
    {
        struct gui_event ev = { 0 };
        ev.type = GUI_EVENT_KEY;
        ev.key = key;
        ev.mods = mods;
        post(win, &ev);
    }
    if (mods & (GUI_MOD_CTRL | GUI_MOD_ALT))
        return;
    char text[64] = "";
    if (win->compose)
    {
        xkb_compose_state_feed(win->compose, sym);
        switch (xkb_compose_state_get_status(win->compose))
        {
        case XKB_COMPOSE_COMPOSING:
            return;   /* a dead key: wait for the next one */
        case XKB_COMPOSE_COMPOSED:
            xkb_compose_state_get_utf8(win->compose, text, sizeof text);
            xkb_compose_state_reset(win->compose);
            post_chars(win, text);
            return;
        case XKB_COMPOSE_CANCELLED:
            xkb_compose_state_reset(win->compose);
            return;
        default:
            break;
        }
    }
    xkb_state_key_get_utf8(win->xkb_state, xkb_key, text, sizeof text);
    post_chars(win, text);
}

static void keyboard_keymap(void* data, struct wl_keyboard* k, uint32_t format, int32_t fd, uint32_t size)
{
    (void)k;
    struct wl_window* win = data;
    if (format != WL_KEYBOARD_KEYMAP_FORMAT_XKB_V1)
    {
        close(fd);
        return;
    }
    char* map = mmap(NULL, size, PROT_READ, MAP_PRIVATE, fd, 0);
    close(fd);
    if (map == MAP_FAILED)
        return;
    struct xkb_keymap* keymap = xkb_keymap_new_from_string(win->xkb, map, XKB_KEYMAP_FORMAT_TEXT_V1,
                                                           XKB_KEYMAP_COMPILE_NO_FLAGS);
    munmap(map, size);
    if (!keymap)
        return;
    if (win->xkb_state)
        xkb_state_unref(win->xkb_state);
    if (win->keymap)
        xkb_keymap_unref(win->keymap);
    win->keymap = keymap;
    win->xkb_state = xkb_state_new(keymap);
}

static void keyboard_enter(void* data, struct wl_keyboard* k, uint32_t serial, struct wl_surface* s,
                           struct wl_array* keys)
{
    (void)k; (void)s; (void)keys;
    struct wl_window* win = data;
    win->serial = serial;
}

static void keyboard_leave(void* data, struct wl_keyboard* k, uint32_t serial, struct wl_surface* s)
{
    (void)k; (void)serial; (void)s;
    struct wl_window* win = data;
    win->repeat_key = 0;
}

static void keyboard_key(void* data, struct wl_keyboard* k, uint32_t serial, uint32_t time, uint32_t key,
                         uint32_t state)
{
    (void)k; (void)time;
    struct wl_window* win = data;
    win->serial = serial;
    if (!win->xkb_state)
        return;
    uint32_t xkb_key = key + 8;
    if (state == WL_KEYBOARD_KEY_STATE_PRESSED)
    {
        key_down(win, xkb_key);
        if (win->repeat_rate > 0 && xkb_keymap_key_repeats(win->keymap, xkb_key))
        {
            win->repeat_key = xkb_key;
            win->repeat_due = now_ms() + win->repeat_delay;
        }
    }
    else if (win->repeat_key == xkb_key)
    {
        win->repeat_key = 0;
    }
}

static void keyboard_modifiers(void* data, struct wl_keyboard* k, uint32_t serial, uint32_t depressed,
                               uint32_t latched, uint32_t locked, uint32_t group)
{
    (void)k; (void)serial;
    struct wl_window* win = data;
    if (win->xkb_state)
        xkb_state_update_mask(win->xkb_state, depressed, latched, locked, 0, 0, group);
}

static void keyboard_repeat_info(void* data, struct wl_keyboard* k, int32_t rate, int32_t delay)
{
    (void)k;
    struct wl_window* win = data;
    win->repeat_rate = rate;
    win->repeat_delay = delay;
}

static const struct wl_keyboard_listener keyboard_listener = {
    .keymap = keyboard_keymap,
    .enter = keyboard_enter,
    .leave = keyboard_leave,
    .key = keyboard_key,
    .modifiers = keyboard_modifiers,
    .repeat_info = keyboard_repeat_info,
};

static void seat_capabilities(void* data, struct wl_seat* seat, uint32_t caps)
{
    struct wl_window* win = data;
    if ((caps & WL_SEAT_CAPABILITY_POINTER) && !win->pointer)
    {
        win->pointer = wl_seat_get_pointer(seat);
        wl_pointer_add_listener(win->pointer, &pointer_listener, win);
    }
    if ((caps & WL_SEAT_CAPABILITY_KEYBOARD) && !win->keyboard)
    {
        win->keyboard = wl_seat_get_keyboard(seat);
        wl_keyboard_add_listener(win->keyboard, &keyboard_listener, win);
    }
}

static void seat_name(void* data, struct wl_seat* seat, const char* name)
{
    (void)data; (void)seat; (void)name;
}

static const struct wl_seat_listener seat_listener = { seat_capabilities, seat_name };

/* --- The window: xdg-shell --- */

static void wm_base_ping(void* data, struct xdg_wm_base* base, uint32_t serial)
{
    (void)data;
    xdg_wm_base_pong(base, serial);
}

static const struct xdg_wm_base_listener wm_base_listener = { wm_base_ping };

static void xdg_surface_configure(void* data, struct xdg_surface* s, uint32_t serial)
{
    struct wl_window* win = data;
    xdg_surface_ack_configure(s, serial);
    if (win->want_w > 0 && win->want_h > 0)
        resize_canvas(win, win->want_w, win->want_h);
    win->configured = 1;
    win->damage = (struct gui_rect){ 0, 0, win->canvas.w, win->canvas.h };
    gui_app_invalidate(win->app);
    win->pending = 1;
}

static const struct xdg_surface_listener xdg_surface_listener = { xdg_surface_configure };

static void toplevel_configure(void* data, struct xdg_toplevel* t, int32_t w, int32_t h, struct wl_array* states)
{
    (void)t; (void)states;
    struct wl_window* win = data;
    win->want_w = w;   /* 0: ours to choose - the size we have */
    win->want_h = h;
}

static void toplevel_close(void* data, struct xdg_toplevel* t)
{
    (void)t;
    struct wl_window* win = data;
    struct gui_event ev = { 0 };
    ev.type = GUI_EVENT_CLOSE;
    post(win, &ev);
}

static void toplevel_configure_bounds(void* data, struct xdg_toplevel* t, int32_t w, int32_t h)
{
    (void)data; (void)t; (void)w; (void)h;
}

static void toplevel_wm_capabilities(void* data, struct xdg_toplevel* t, struct wl_array* caps)
{
    (void)data; (void)t; (void)caps;
}

static const struct xdg_toplevel_listener toplevel_listener = {
    .configure = toplevel_configure,
    .close = toplevel_close,
    .configure_bounds = toplevel_configure_bounds,
    .wm_capabilities = toplevel_wm_capabilities,
};

static void registry_global(void* data, struct wl_registry* reg, uint32_t name, const char* iface, uint32_t version)
{
    struct wl_window* win = data;
    if (strcmp(iface, wl_compositor_interface.name) == 0)
        win->compositor = wl_registry_bind(reg, name, &wl_compositor_interface, version < 4 ? version : 4);
    else if (strcmp(iface, wl_shm_interface.name) == 0)
        win->shm = wl_registry_bind(reg, name, &wl_shm_interface, 1);
    else if (strcmp(iface, wl_seat_interface.name) == 0 && !win->seat)
    {
        win->seat = wl_registry_bind(reg, name, &wl_seat_interface, version < 5 ? version : 5);
        wl_seat_add_listener(win->seat, &seat_listener, win);
    }
    else if (strcmp(iface, xdg_wm_base_interface.name) == 0)
    {
        win->wm_base = wl_registry_bind(reg, name, &xdg_wm_base_interface, 1);
        xdg_wm_base_add_listener(win->wm_base, &wm_base_listener, win);
    }
    else if (strcmp(iface, zxdg_decoration_manager_v1_interface.name) == 0)
        win->decoration_manager = wl_registry_bind(reg, name, &zxdg_decoration_manager_v1_interface, 1);
    else if (strcmp(iface, wl_data_device_manager_interface.name) == 0)
        win->data_manager = wl_registry_bind(reg, name, &wl_data_device_manager_interface, version < 3 ? version : 3);
}

static void registry_remove(void* data, struct wl_registry* reg, uint32_t name)
{
    (void)data; (void)reg; (void)name;
}

static const struct wl_registry_listener registry_listener = { registry_global, registry_remove };

/* --- The loop --- */

/* Waits for the compositor, the app's timer or the key repeat. */
static void wait_event(struct wl_window* win)
{
    while (wl_display_prepare_read(win->display) != 0)
        wl_display_dispatch_pending(win->display);
    wl_display_flush(win->display);
    long long due = -1;
    if (win->timer_ms > 0)
        due = win->timer_due;
    if (win->repeat_key && (due < 0 || win->repeat_due < due))
        due = win->repeat_due;
    int timeout = -1;
    if (due >= 0)
    {
        long long left = due - now_ms();
        timeout = left > 0 ? (int)left : 0;
    }
    struct pollfd p = { wl_display_get_fd(win->display), POLLIN, 0 };
    if (poll(&p, 1, timeout) > 0)
        wl_display_read_events(win->display);
    else
        wl_display_cancel_read(win->display);
    wl_display_dispatch_pending(win->display);
}

int main(int argc, char** argv)
{
    setlocale(LC_ALL, "");

    struct wl_window win = { 0 };
    struct gui_canvas* c = &win.canvas;
    c->win = &win;
    win.display = wl_display_connect(NULL);
    if (!win.display)
    {
        fprintf(stderr, "cannot connect to the Wayland display\n");
        return 1;
    }
    win.registry = wl_display_get_registry(win.display);
    wl_registry_add_listener(win.registry, &registry_listener, &win);
    wl_display_roundtrip(win.display);
    if (!win.compositor || !win.shm || !win.wm_base)
    {
        fprintf(stderr, "the compositor lacks wl_compositor, wl_shm or xdg_wm_base\n");
        return 1;
    }
    win.xkb = xkb_context_new(XKB_CONTEXT_NO_FLAGS);
    const char* locale = getenv("LC_ALL");
    if (!locale || !*locale) locale = getenv("LC_CTYPE");
    if (!locale || !*locale) locale = getenv("LANG");
    if (!locale || !*locale) locale = "C";
    win.compose_table = xkb_compose_table_new_from_locale(win.xkb, locale, XKB_COMPOSE_COMPILE_NO_FLAGS);
    if (win.compose_table)
        win.compose = xkb_compose_state_new(win.compose_table, XKB_COMPOSE_STATE_NO_FLAGS);
    if (win.seat && win.data_manager)
    {
        win.data_device = wl_data_device_manager_get_data_device(win.data_manager, win.seat);
        wl_data_device_add_listener(win.data_device, &device_listener, &win);
    }

    FcInit();
    if (FT_Init_FreeType(&c->ft))
    {
        fprintf(stderr, "cannot start FreeType\n");
        return 1;
    }
    c->pt = DEFAULT_FONT_PT;
    if (!apply_font(c))
    {
        fprintf(stderr, "no usable font (is fontconfig installed?)\n");
        return 1;
    }
    resize_canvas(&win, DEFAULT_COLS * c->main.metrics.cell_w, DEFAULT_ROWS * c->main.metrics.cell_h);

    win.surface = wl_compositor_create_surface(win.compositor);
    win.xdg_surface = xdg_wm_base_get_xdg_surface(win.wm_base, win.surface);
    xdg_surface_add_listener(win.xdg_surface, &xdg_surface_listener, &win);
    win.toplevel = xdg_surface_get_toplevel(win.xdg_surface);
    xdg_toplevel_add_listener(win.toplevel, &toplevel_listener, &win);
    xdg_toplevel_set_title(win.toplevel, "Cake " CAKE_VERSION);
    xdg_toplevel_set_app_id(win.toplevel, "cakeide");
    if (win.decoration_manager)
    {
        /* the compositor's title bar and borders, where it draws them */
        struct zxdg_toplevel_decoration_v1* deco =
            zxdg_decoration_manager_v1_get_toplevel_decoration(win.decoration_manager, win.toplevel);
        zxdg_toplevel_decoration_v1_set_mode(deco, ZXDG_TOPLEVEL_DECORATION_V1_MODE_SERVER_SIDE);
    }
    const char* size = getenv("XCURSOR_SIZE");
    win.cursor_theme = wl_cursor_theme_load(getenv("XCURSOR_THEME"), size && atoi(size) > 0 ? atoi(size) : 24, win.shm);
    win.cursor_surface = wl_compositor_create_surface(win.compositor);
    wl_surface_commit(win.surface);   /* the first configure answers this */

    win.app = gui_app_create();
    offer_fonts(&win);
    gui_app_start(win.app, c, argc, argv);
    gui_app_resize(win.app, c->w, c->h);
    win.running = 1;
    wl_display_roundtrip(win.display);

    while (win.running)
    {
        if (win.pending)
        {
            win.pending = 0;
            refresh(&win);   /* once for everything taken */
            if (!win.running)
                break;
        }
        wait_event(&win);
        if (wl_display_get_error(win.display))
            break;   /* the compositor went away */
        long long now = now_ms();
        if (win.timer_ms > 0 && now >= win.timer_due)
        {
            win.timer_due = now + win.timer_ms;
            struct gui_event ev = { 0 };
            ev.type = GUI_EVENT_TIMER;
            post(&win, &ev);
        }
        if (win.repeat_key && now >= win.repeat_due)
        {
            win.repeat_due = now + (win.repeat_rate > 0 ? 1000 / win.repeat_rate : 40);
            key_down(&win, win.repeat_key);
        }
        if (win.frame_pending)
            present(&win);   /* a buffer came back: show what waited */
    }

    gui_app_free(win.app);
    for (int i = 0; i < 2; i++)
        buffer_destroy(&win.buffers[i]);
    font_free(&c->main);
    font_free(&c->small_font);
    FT_Done_FreeType(c->ft);
    free(c->pixels);
    free(c->clip_text);
    if (win.compose) xkb_compose_state_unref(win.compose);
    if (win.compose_table) xkb_compose_table_unref(win.compose_table);
    if (win.xkb_state) xkb_state_unref(win.xkb_state);
    if (win.keymap) xkb_keymap_unref(win.keymap);
    if (win.xkb) xkb_context_unref(win.xkb);
    if (win.cursor_theme) wl_cursor_theme_destroy(win.cursor_theme);
    xdg_toplevel_destroy(win.toplevel);
    xdg_surface_destroy(win.xdg_surface);
    wl_surface_destroy(win.surface);
    wl_display_disconnect(win.display);
    return 0;
}
