//This was generated by running cake -autoconfig 
//This file was generated reading the variable INCLUDE inside Visual Studio Command Prompt.
//echo %INCLUDE% 
#pragma dir "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/include/"
#pragma dir "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Tools/MSVC/14.44.35207/ATLMFC/include/"
#pragma dir "C:/Program Files/Microsoft Visual Studio/2022/Community/VC/Auxiliary/VS/include/"
#pragma dir "C:/Program Files (x86)/Windows Kits/10/include/10.0.26100.0/ucrt/"
#pragma dir "C:/Program Files (x86)/Windows Kits/10//include/10.0.26100.0//um/"
#pragma dir "C:/Program Files (x86)/Windows Kits/10//include/10.0.26100.0//shared/"
#pragma dir "C:/Program Files (x86)/Windows Kits/10//include/10.0.26100.0//winrt/"
#pragma dir "C:/Program Files (x86)/Windows Kits/10//include/10.0.26100.0//cppwinrt/"
