//This was generated by running cake -autoconfig 
//This file was generated reading the output of
//echo | clang -v -E - 2>&1

#pragma dir "/Library/Developer/CommandLineTools/usr/lib/clang/21/include"
#pragma dir "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include"
#pragma dir "/Library/Developer/CommandLineTools/usr/include"
#pragma dir "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks (framework directory)"
#pragma dir "/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/SubFrameworks (framework directory)"

