//This was generated by running cake -autoconfig 
This file was generated reading the output of
//echo | gcc -v -E - 2>&1

#pragma dir "/usr/lib/gcc/x86_64-linux-gnu/11/include"
#pragma dir "/usr/local/include"
#pragma dir "/usr/include/x86_64-linux-gnu"
#pragma dir "/usr/include"

