#pragma once


enum object_type
{
    TYPE_SIGNED_CHAR,
    TYPE_UNSIGNED_CHAR,

    TYPE_SIGNED_SHORT,
    TYPE_UNSIGNED_SHORT,

    TYPE_SIGNED_INT,
    TYPE_UNSIGNED_INT,

    TYPE_SIGNED_LONG,
    TYPE_UNSIGNED_LONG,

    TYPE_SIGNED_LONG_LONG,
    TYPE_UNSIGNED_LONG_LONG,

    TYPE_FLOAT,
    TYPE_DOUBLE,
    TYPE_LONG_DOUBLE,

    /* unsigned bitfield = TYPE_UNSIGNED_BITFIELD_1 (13) ... TYPE_UNSIGNED_BITFIELD_128 (140)*/
    
    TYPE_UNSIGNED_BITFIELD_1, TYPE_UNSIGNED_BITFIELD_2, TYPE_UNSIGNED_BITFIELD_3, TYPE_UNSIGNED_BITFIELD_4, TYPE_UNSIGNED_BITFIELD_5, TYPE_UNSIGNED_BITFIELD_6, TYPE_UNSIGNED_BITFIELD_7, TYPE_UNSIGNED_BITFIELD_8, TYPE_UNSIGNED_BITFIELD_9, TYPE_UNSIGNED_BITFIELD_10,
    TYPE_UNSIGNED_BITFIELD_11, TYPE_UNSIGNED_BITFIELD_12, TYPE_UNSIGNED_BITFIELD_13, TYPE_UNSIGNED_BITFIELD_14, TYPE_UNSIGNED_BITFIELD_15, TYPE_UNSIGNED_BITFIELD_16, TYPE_UNSIGNED_BITFIELD_17, TYPE_UNSIGNED_BITFIELD_18, TYPE_UNSIGNED_BITFIELD_19, TYPE_UNSIGNED_BITFIELD_20,
    TYPE_UNSIGNED_BITFIELD_21, TYPE_UNSIGNED_BITFIELD_22, TYPE_UNSIGNED_BITFIELD_23, TYPE_UNSIGNED_BITFIELD_24, TYPE_UNSIGNED_BITFIELD_25, TYPE_UNSIGNED_BITFIELD_26, TYPE_UNSIGNED_BITFIELD_27, TYPE_UNSIGNED_BITFIELD_28, TYPE_UNSIGNED_BITFIELD_29, TYPE_UNSIGNED_BITFIELD_30,
    TYPE_UNSIGNED_BITFIELD_31, TYPE_UNSIGNED_BITFIELD_32, TYPE_UNSIGNED_BITFIELD_33, TYPE_UNSIGNED_BITFIELD_34, TYPE_UNSIGNED_BITFIELD_35, TYPE_UNSIGNED_BITFIELD_36, TYPE_UNSIGNED_BITFIELD_37, TYPE_UNSIGNED_BITFIELD_38, TYPE_UNSIGNED_BITFIELD_39, TYPE_UNSIGNED_BITFIELD_40,
    TYPE_UNSIGNED_BITFIELD_41, TYPE_UNSIGNED_BITFIELD_42, TYPE_UNSIGNED_BITFIELD_43, TYPE_UNSIGNED_BITFIELD_44, TYPE_UNSIGNED_BITFIELD_45, TYPE_UNSIGNED_BITFIELD_46, TYPE_UNSIGNED_BITFIELD_47, TYPE_UNSIGNED_BITFIELD_48, TYPE_UNSIGNED_BITFIELD_49, TYPE_UNSIGNED_BITFIELD_50,
    TYPE_UNSIGNED_BITFIELD_51, TYPE_UNSIGNED_BITFIELD_52, TYPE_UNSIGNED_BITFIELD_53, TYPE_UNSIGNED_BITFIELD_54, TYPE_UNSIGNED_BITFIELD_55, TYPE_UNSIGNED_BITFIELD_56, TYPE_UNSIGNED_BITFIELD_57, TYPE_UNSIGNED_BITFIELD_58, TYPE_UNSIGNED_BITFIELD_59, TYPE_UNSIGNED_BITFIELD_60,
    TYPE_UNSIGNED_BITFIELD_61, TYPE_UNSIGNED_BITFIELD_62, TYPE_UNSIGNED_BITFIELD_63, TYPE_UNSIGNED_BITFIELD_64, TYPE_UNSIGNED_BITFIELD_65, TYPE_UNSIGNED_BITFIELD_66, TYPE_UNSIGNED_BITFIELD_67, TYPE_UNSIGNED_BITFIELD_68, TYPE_UNSIGNED_BITFIELD_69, TYPE_UNSIGNED_BITFIELD_70,
    TYPE_UNSIGNED_BITFIELD_71, TYPE_UNSIGNED_BITFIELD_72, TYPE_UNSIGNED_BITFIELD_73, TYPE_UNSIGNED_BITFIELD_74, TYPE_UNSIGNED_BITFIELD_75, TYPE_UNSIGNED_BITFIELD_76, TYPE_UNSIGNED_BITFIELD_77, TYPE_UNSIGNED_BITFIELD_78, TYPE_UNSIGNED_BITFIELD_79, TYPE_UNSIGNED_BITFIELD_80,
    TYPE_UNSIGNED_BITFIELD_81, TYPE_UNSIGNED_BITFIELD_82, TYPE_UNSIGNED_BITFIELD_83, TYPE_UNSIGNED_BITFIELD_84, TYPE_UNSIGNED_BITFIELD_85, TYPE_UNSIGNED_BITFIELD_86, TYPE_UNSIGNED_BITFIELD_87, TYPE_UNSIGNED_BITFIELD_88, TYPE_UNSIGNED_BITFIELD_89, TYPE_UNSIGNED_BITFIELD_90,
    TYPE_UNSIGNED_BITFIELD_91, TYPE_UNSIGNED_BITFIELD_92, TYPE_UNSIGNED_BITFIELD_93, TYPE_UNSIGNED_BITFIELD_94, TYPE_UNSIGNED_BITFIELD_95, TYPE_UNSIGNED_BITFIELD_96, TYPE_UNSIGNED_BITFIELD_97, TYPE_UNSIGNED_BITFIELD_98, TYPE_UNSIGNED_BITFIELD_99, TYPE_UNSIGNED_BITFIELD_100,
    TYPE_UNSIGNED_BITFIELD_101, TYPE_UNSIGNED_BITFIELD_102, TYPE_UNSIGNED_BITFIELD_103, TYPE_UNSIGNED_BITFIELD_104, TYPE_UNSIGNED_BITFIELD_105, TYPE_UNSIGNED_BITFIELD_106, TYPE_UNSIGNED_BITFIELD_107, TYPE_UNSIGNED_BITFIELD_108, TYPE_UNSIGNED_BITFIELD_109, TYPE_UNSIGNED_BITFIELD_110,
    TYPE_UNSIGNED_BITFIELD_111, TYPE_UNSIGNED_BITFIELD_112, TYPE_UNSIGNED_BITFIELD_113, TYPE_UNSIGNED_BITFIELD_114, TYPE_UNSIGNED_BITFIELD_115, TYPE_UNSIGNED_BITFIELD_116, TYPE_UNSIGNED_BITFIELD_117, TYPE_UNSIGNED_BITFIELD_118, TYPE_UNSIGNED_BITFIELD_119, TYPE_UNSIGNED_BITFIELD_120,
    TYPE_UNSIGNED_BITFIELD_121, TYPE_UNSIGNED_BITFIELD_122, TYPE_UNSIGNED_BITFIELD_123, TYPE_UNSIGNED_BITFIELD_124, TYPE_UNSIGNED_BITFIELD_125, TYPE_UNSIGNED_BITFIELD_126, TYPE_UNSIGNED_BITFIELD_127, TYPE_UNSIGNED_BITFIELD_128,

    /* signed bitfield = TYPE_SIGNED_BITFIELD_1(141) ... TYPE_SIGNED_BITFIELD_128 (268)*/
    
    TYPE_SIGNED_BITFIELD_1, TYPE_SIGNED_BITFIELD_2, TYPE_SIGNED_BITFIELD_3, TYPE_SIGNED_BITFIELD_4, TYPE_SIGNED_BITFIELD_5, TYPE_SIGNED_BITFIELD_6, TYPE_SIGNED_BITFIELD_7, TYPE_SIGNED_BITFIELD_8, TYPE_SIGNED_BITFIELD_9, TYPE_SIGNED_BITFIELD_10,
    TYPE_SIGNED_BITFIELD_11, TYPE_SIGNED_BITFIELD_12, TYPE_SIGNED_BITFIELD_13, TYPE_SIGNED_BITFIELD_14, TYPE_SIGNED_BITFIELD_15, TYPE_SIGNED_BITFIELD_16, TYPE_SIGNED_BITFIELD_17, TYPE_SIGNED_BITFIELD_18, TYPE_SIGNED_BITFIELD_19, TYPE_SIGNED_BITFIELD_20,
    TYPE_SIGNED_BITFIELD_21, TYPE_SIGNED_BITFIELD_22, TYPE_SIGNED_BITFIELD_23, TYPE_SIGNED_BITFIELD_24, TYPE_SIGNED_BITFIELD_25, TYPE_SIGNED_BITFIELD_26, TYPE_SIGNED_BITFIELD_27, TYPE_SIGNED_BITFIELD_28, TYPE_SIGNED_BITFIELD_29, TYPE_SIGNED_BITFIELD_30,
    TYPE_SIGNED_BITFIELD_31, TYPE_SIGNED_BITFIELD_32, TYPE_SIGNED_BITFIELD_33, TYPE_SIGNED_BITFIELD_34, TYPE_SIGNED_BITFIELD_35, TYPE_SIGNED_BITFIELD_36, TYPE_SIGNED_BITFIELD_37, TYPE_SIGNED_BITFIELD_38, TYPE_SIGNED_BITFIELD_39, TYPE_SIGNED_BITFIELD_40,
    TYPE_SIGNED_BITFIELD_41, TYPE_SIGNED_BITFIELD_42, TYPE_SIGNED_BITFIELD_43, TYPE_SIGNED_BITFIELD_44, TYPE_SIGNED_BITFIELD_45, TYPE_SIGNED_BITFIELD_46, TYPE_SIGNED_BITFIELD_47, TYPE_SIGNED_BITFIELD_48, TYPE_SIGNED_BITFIELD_49, TYPE_SIGNED_BITFIELD_50,
    TYPE_SIGNED_BITFIELD_51, TYPE_SIGNED_BITFIELD_52, TYPE_SIGNED_BITFIELD_53, TYPE_SIGNED_BITFIELD_54, TYPE_SIGNED_BITFIELD_55, TYPE_SIGNED_BITFIELD_56, TYPE_SIGNED_BITFIELD_57, TYPE_SIGNED_BITFIELD_58, TYPE_SIGNED_BITFIELD_59, TYPE_SIGNED_BITFIELD_60,
    TYPE_SIGNED_BITFIELD_61, TYPE_SIGNED_BITFIELD_62, TYPE_SIGNED_BITFIELD_63, TYPE_SIGNED_BITFIELD_64, TYPE_SIGNED_BITFIELD_65, TYPE_SIGNED_BITFIELD_66, TYPE_SIGNED_BITFIELD_67, TYPE_SIGNED_BITFIELD_68, TYPE_SIGNED_BITFIELD_69, TYPE_SIGNED_BITFIELD_70,
    TYPE_SIGNED_BITFIELD_71, TYPE_SIGNED_BITFIELD_72, TYPE_SIGNED_BITFIELD_73, TYPE_SIGNED_BITFIELD_74, TYPE_SIGNED_BITFIELD_75, TYPE_SIGNED_BITFIELD_76, TYPE_SIGNED_BITFIELD_77, TYPE_SIGNED_BITFIELD_78, TYPE_SIGNED_BITFIELD_79, TYPE_SIGNED_BITFIELD_80,
    TYPE_SIGNED_BITFIELD_81, TYPE_SIGNED_BITFIELD_82, TYPE_SIGNED_BITFIELD_83, TYPE_SIGNED_BITFIELD_84, TYPE_SIGNED_BITFIELD_85, TYPE_SIGNED_BITFIELD_86, TYPE_SIGNED_BITFIELD_87, TYPE_SIGNED_BITFIELD_88, TYPE_SIGNED_BITFIELD_89, TYPE_SIGNED_BITFIELD_90,
    TYPE_SIGNED_BITFIELD_91, TYPE_SIGNED_BITFIELD_92, TYPE_SIGNED_BITFIELD_93, TYPE_SIGNED_BITFIELD_94, TYPE_SIGNED_BITFIELD_95, TYPE_SIGNED_BITFIELD_96, TYPE_SIGNED_BITFIELD_97, TYPE_SIGNED_BITFIELD_98, TYPE_SIGNED_BITFIELD_99, TYPE_SIGNED_BITFIELD_100,
    TYPE_SIGNED_BITFIELD_101, TYPE_SIGNED_BITFIELD_102, TYPE_SIGNED_BITFIELD_103, TYPE_SIGNED_BITFIELD_104, TYPE_SIGNED_BITFIELD_105, TYPE_SIGNED_BITFIELD_106, TYPE_SIGNED_BITFIELD_107, TYPE_SIGNED_BITFIELD_108, TYPE_SIGNED_BITFIELD_109, TYPE_SIGNED_BITFIELD_110,
    TYPE_SIGNED_BITFIELD_111, TYPE_SIGNED_BITFIELD_112, TYPE_SIGNED_BITFIELD_113, TYPE_SIGNED_BITFIELD_114, TYPE_SIGNED_BITFIELD_115, TYPE_SIGNED_BITFIELD_116, TYPE_SIGNED_BITFIELD_117, TYPE_SIGNED_BITFIELD_118, TYPE_SIGNED_BITFIELD_119, TYPE_SIGNED_BITFIELD_120,
    TYPE_SIGNED_BITFIELD_121, TYPE_SIGNED_BITFIELD_122, TYPE_SIGNED_BITFIELD_123, TYPE_SIGNED_BITFIELD_124, TYPE_SIGNED_BITFIELD_125, TYPE_SIGNED_BITFIELD_126, TYPE_SIGNED_BITFIELD_127, TYPE_SIGNED_BITFIELD_128,

    
};


enum target
{
    TARGET_X86_X64_GCC,
    TARGET_X86_MSVC,
    TARGET_X64_MSVC,
    TARGET_CCU8,
    TARGET_LCCU16,
    TARGET_CATALINA,

};
#define NUMBER_OF_TARGETS  6

struct platform
{
    const char* name;

    const char* thread_local_attr;
    const char* alignas_fmt_must_have_one_percent_d;

    int bool_n_bits;
    int bool_alignment;
    enum object_type bool_type;

    int char_n_bits;
    enum object_type char_t_type;
    int char_alignment;

    int short_n_bits;
    int short_alignment;

    int int_n_bits;
    int int_alignment;

    int long_n_bits;
    int long_alignment;

    int long_long_n_bits;
    int long_long_alignment;

    int float_n_bits;
    int float_alignment;

    int double_n_bits;
    int double_alignment;

    int long_double_n_bits;
    int long_double_alignment;

    int pointer_n_bits;
    int pointer_alignment;

    /*typedefs*/
    enum object_type wchar_t_type;
    enum object_type int8_type;
    enum object_type int16_type;
    enum object_type int32_type;
    enum object_type int64_type;

    enum object_type size_t_type;
    enum object_type ptrdiff_type;
};


int parse_target(const char* targetstr, enum target* target);
void print_target_options();
struct platform* get_platform(enum  target target);
int target_get_num_of_bits(enum target target, enum object_type type);
int parse_target(const char* targetstr, enum target* target);
void print_target_options();
const char* target_get_predefined_macros(enum target e);
const char* target_get_builtins(enum target e);


long long target_signed_max(enum  target target, enum object_type type);
long long target_signed_min(enum  target target, enum object_type type);

unsigned long long target_unsigned_max(enum  target target, enum object_type type);


#if defined(_WIN32) && defined(_WIN64)
#define CAKE_COMPILE_TIME_SELECTED_TARGET TARGET_X64_MSVC
#endif

#if defined(_WIN32) && !defined(_WIN64)
#define CAKE_COMPILE_TIME_SELECTED_TARGET TARGET_X86_MSVC
#endif

#if !defined(_WIN32) && (defined(__x86_64__) || defined(_M_X64))
#define CAKE_COMPILE_TIME_SELECTED_TARGET TARGET_X86_X64_GCC
#endif

#ifdef __EMSCRIPTEN__
#define CAKE_COMPILE_TIME_SELECTED_TARGET TARGET_X86_X64_GCC
#endif

#if defined(__APPLE__) && defined(__MACH__)
#define CAKE_COMPILE_TIME_SELECTED_TARGET TARGET_X86_X64_GCC
#endif
