#define __EI()
#define __DI()
#define __asm()
#define __SEGBASE_N()
#define __SEGBASE_F()
#define __SEGSIZE()
#define __near
#define __far
#define __huge
#define __PACKED
#define __UNPACKED
#define __noreg
#define __STDC__
#define __CCU8__
#define __VERSION__
#define __ARCHITECTURE__
#define __DEBUG__
#define __MS__
#define __ML__
#define __ML__
#define __UNSIGNEDCHAR__
#define __NOFAR__
#define __LCCU16__
#define __LAPISOMF__
