#pragma once

 unsigned int stdc_leading_zeros_uc(unsigned char value);
 unsigned int stdc_leading_zeros_us(unsigned short value);
 unsigned int stdc_leading_zeros_ui(unsigned int value);
 unsigned int stdc_leading_zeros_ul(unsigned long value);
 unsigned int stdc_leading_zeros_ull(unsigned long long value);
 //generic_return_type stdc_leading_zeros(generic_value_type value);
 unsigned int stdc_leading_ones_uc(unsigned char value);
 unsigned int stdc_leading_ones_us(unsigned short value);
 unsigned int stdc_leading_ones_ui(unsigned int value);
 unsigned int stdc_leading_ones_ul(unsigned long value);
 unsigned int stdc_leading_ones_ull(unsigned long long value);
 //generic_return_type stdc_leading_ones(generic_value_type value);
 unsigned int stdc_trailing_zeros_uc(unsigned char value);
 unsigned int stdc_trailing_zeros_us(unsigned short value);
 unsigned int stdc_trailing_zeros_ui(unsigned int value);
 unsigned int stdc_trailing_zeros_ul(unsigned long value);
 unsigned int stdc_trailing_zeros_ull(unsigned long long value);
 //generic_return_type stdc_trailing_zeros(generic_value_type value);
 unsigned int stdc_trailing_ones_uc(unsigned char value);
 unsigned int stdc_trailing_ones_us(unsigned short value);
 unsigned int stdc_trailing_ones_ui(unsigned int value);
 unsigned int stdc_trailing_ones_ul(unsigned long value);
 unsigned int stdc_trailing_ones_ull(unsigned long long value);
 //generic_return_type stdc_trailing_ones(generic_value_type value);
 unsigned int stdc_first_leading_zero_uc(unsigned char value);
 unsigned int stdc_first_leading_zero_us(unsigned short value);
 unsigned int stdc_first_leading_zero_ui(unsigned int value);
 unsigned int stdc_first_leading_zero_ul(unsigned long value);
 unsigned int stdc_first_leading_zero_ull(unsigned long long value);
 //generic_return_type stdc_first_leading_zero(generic_value_type value);
 unsigned int stdc_first_leading_one_uc(unsigned char value);
 unsigned int stdc_first_leading_one_us(unsigned short value);
 unsigned int stdc_first_leading_one_ui(unsigned int value);
 unsigned int stdc_first_leading_one_ul(unsigned long value);
 unsigned int stdc_first_leading_one_ull(unsigned long long value);
 //generic_return_type stdc_first_leading_one(generic_value_type value);
 unsigned int stdc_first_trailing_zero_uc(unsigned char value);
 unsigned int stdc_first_trailing_zero_us(unsigned short value);
 unsigned int stdc_first_trailing_zero_ui(unsigned int value);
 unsigned int stdc_first_trailing_zero_ul(unsigned long value);
 unsigned int stdc_first_trailing_zero_ull(unsigned long long value);
 //generic_return_type stdc_first_trailing_zero(generic_value_type value);
 unsigned int stdc_first_trailing_one_uc(unsigned char value);
 unsigned int stdc_first_trailing_one_us(unsigned short value);
 unsigned int stdc_first_trailing_one_ui(unsigned int value);
 unsigned int stdc_first_trailing_one_ul(unsigned long value);
 unsigned int stdc_first_trailing_one_ull(unsigned long long value);
 //generic_return_type stdc_first_trailing_one(generic_value_type value);
 unsigned int stdc_count_zeros_uc(unsigned char value);
 unsigned int stdc_count_zeros_us(unsigned short value);
 unsigned int stdc_count_zeros_ui(unsigned int value);
 unsigned int stdc_count_zeros_ul(unsigned long value);
 unsigned int stdc_count_zeros_ull(unsigned long long value);
 //generic_return_type stdc_count_zeros(generic_value_type value);
 unsigned int stdc_count_ones_uc(unsigned char value);
 unsigned int stdc_count_ones_us(unsigned short value);
 unsigned int stdc_count_ones_ui(unsigned int value);
 unsigned int stdc_count_ones_ul(unsigned long value);
 unsigned int stdc_count_ones_ull(unsigned long long value);
 //generic_return_type stdc_count_ones(generic_value_type value);
 bool stdc_has_single_bit_uc(unsigned char value);
 bool stdc_has_single_bit_us(unsigned short value);
 bool stdc_has_single_bit_ui(unsigned int value);
 bool stdc_has_single_bit_ul(unsigned long value);
 bool stdc_has_single_bit_ull(unsigned long long value);
 //bool stdc_has_single_bit(generic_value_type value);
 unsigned int stdc_bit_width_uc(unsigned char value);
 unsigned int stdc_bit_width_us(unsigned short value);
 unsigned int stdc_bit_width_ui(unsigned int value);
 unsigned int stdc_bit_width_ul(unsigned long value);
 unsigned int stdc_bit_width_ull(unsigned long long value);
 //generic_return_type stdc_bit_width(generic_value_type value);
 unsigned char stdc_bit_floor_uc(unsigned char value);
 unsigned short stdc_bit_floor_us(unsigned short value);
 unsigned int stdc_bit_floor_ui(unsigned int value);
 unsigned long stdc_bit_floor_ul(unsigned long value);
 unsigned long long stdc_bit_floor_ull(unsigned long long value);
 //generic_value_type stdc_bit_floor(generic_value_type value);
 unsigned char stdc_bit_ceil_uc(unsigned char value);
 unsigned short stdc_bit_ceil_us(unsigned short value);
 unsigned int stdc_bit_ceil_ui(unsigned int value);
 unsigned long stdc_bit_ceil_ul(unsigned long value);
 unsigned long long stdc_bit_ceil_ull(unsigned long long value);
 //generic_value_type stdc_bit_ceil(generic_value_type value);

